# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: main
        run: |
          TMPFILE=$(mktemp);for f in *.csv; do (tail -n +2 -q "${f}"|sort -uf; echo) >> $TMPFILE;done; sort -uf $TMPFILE | sed '/^[[:space:]]*$/d' | sed '1s/^/Account address,Show boosts\n/' > all.csv
          cp all.csv "${{ steps.main.outputs.artifact_dir }}/${{ steps.main.outputs.artifact_build_name }}.csv"

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.artifact_generic_name }}
          path: ${{ steps.build.outputs.artifact_dir }}
