name: Artifacts
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: main
        run: |
          TMPFILE=$(mktemp)
          mkdir -p artifacts
          for f in *.csv; do (tail -n +2 -q "${f}"; echo) >> $TMPFILE;done
          sort -uf $TMPFILE | sed '/^[[:space:]]*$/d' | sed '1s/^/Account address,Show boosts\n/' > aws-all.csv
          cp *.csv artifacts/
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: AWSMastodonList
          path: artifacts/
